name:                agda-language-server
version:             0.1.0.0
github:              "banacorn/agda-language-server"
license:             MIT
author:              "Ting-Gian LUA"
maintainer:          "banacorn@gmail.com"
copyright:           "2020 Author name here :)"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/banacorn/agda-language-server#readme>

dependencies:
  - base >= 4.7 && < 5
  - Agda
  - aeson
  - lsp
  - mtl
  - network
  - network-simple
  - text
  - process

library:
  source-dirs: src

executables:
  als:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agda-language-server

tests:
  als-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agda-language-server
