resolver: lts-11.7

packages:
- location: .
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: e49fc23230017085b450b8dcc2c5a157ef509174
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []
