# # modified from https://github.com/simonmichael/hledger/blob/master/.github/workflows/release.yml

# # Creates a draft github release.
# # See https://github.com/actions/create-release, still pretty rough as of 20200609.
# # see also: https://github.com/marketplace/actions/tag-release-on-push-action

# name: Release

# # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
# on:
#   push:
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# jobs:
#   release:
#     name: Create Github Release
#     if: contains(github.ref, 'tags/v')
#     runs-on: ubuntu-latest
#     steps:
#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@v1.0.0
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ github.ref }}
#         release_name: ${{ github.ref }}
#         draft: false
#         prerelease: false