# modified from https://github.com/simonmichael/hledger/blob/master/.github/workflows/mac.yml

name: CI (macOS)

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        stack-ver: [latest]
        ghc-ver: [8.10.7]
    runs-on: ${{ matrix.os }}

    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v2

    # things to be cached/restored:

    - name: 💾 Cache stack global package db
      id:   stack-global
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-after20210110-${{ hashFiles('**.yaml') }}
    - name: 💾 Cache stack-installed programs in ~/.local/bin
      id:   stack-programs
      uses: actions/cache@v2
      with:
        path: ~/.local/bin
        key: ${{ runner.os }}-stack-programs-${{ hashFiles('**.yaml') }}
    - name: 💾 Cache .stack-work
      uses: actions/cache@v2
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('**.yaml') }}
    - name: 💾 Cache agda-language-server/.stack-work
      uses: actions/cache@v2
      with:
        path: agda-language-server/.stack-work
        key: ${{ runner.os }}-agda-language-server-stack-work-${{ hashFiles('agda-language-server/package.yaml') }}

    # actions:
    #
    - id: haskell-setup
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        stack-version: latest
        enable-stack: true
        stack-no-global: true
        stack-setup-ghc: true

    - name: ⏬ Install dependencies
      run: |
        stack build --flag Agda:optimise-heavily --only-dependencies

    - name: 🔨 Build and run tests
      run: |
        stack test --flag Agda:optimise-heavily

    - name: 📦 Compress files
      id: zip
      run: |
        # locate the data-dir
        datadir=$(find $(stack path --snapshot-install-root)/share -type d -name "Agda-*")
        
        # locate the executable 
        executable=$(find $(stack path --local-install-root)/bin -name "als")

        # make a temporary directory for compresssing
        mkdir zip
        cp -r $datadir zip/data
        cp $executable zip/
        
        # compress
        cd zip 
        zip -r als-macos.zip *
        cd .. 
        mv zip/als-macos.zip .

    - name: 🚢 Release Artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') # so that only commits with a git tag would upload artifacts
      with:
        files: als-macos.zip
        draft: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
